export type ServiceData = {
  slug: string;
  name: string;
  tagline: string;
  category: string;
  icon: string;
  metaDescription: string;
  heroBody: string;
  features: { icon: string; title: string; body: string }[];
  benefits: string[];
  existingPage?: string;
};

export const servicesData: ServiceData[] = [
  // ── Restaurant Technology ──────────────────────────────────────
  {
    slug: "online-ordering",
    name: "Online Ordering",
    tagline: "Commission-Free Ordering",
    category: "Restaurant Technology",
    icon: "🛒",
    metaDescription: "Commission-free online ordering for restaurants. Accept orders from your website with 0% fees. Setup in minutes.",
    heroBody: "Take orders directly from your website with zero commission. No more paying 15–30% to third-party platforms.",
    features: [],
    benefits: [],
    existingPage: "/restaurants/ordering",
  },
  {
    slug: "pos-systems",
    name: "POS Systems",
    tagline: "Oracle Partner",
    category: "Restaurant Technology",
    icon: "🖥️",
    metaDescription: "Restaurant POS systems by an Oracle MICROS partner. Free hardware starter kit, fast setup, table service layouts.",
    heroBody: "Oracle MICROS point-of-sale systems for restaurants — free hardware, fast setup, built for table service.",
    features: [],
    benefits: [],
    existingPage: "/restaurants/pos",
  },
  {
    slug: "digital-signage",
    name: "Digital Signage",
    tagline: "Powered by Yodeck",
    category: "Restaurant Technology",
    icon: "📺",
    metaDescription: "Digital menu boards and restaurant signage powered by Yodeck. Manage all screens remotely.",
    heroBody: "Turn any TV into a dynamic menu board or promotional display, managed remotely from any device.",
    features: [],
    benefits: [],
    existingPage: "/restaurants/signage",
  },
  {
    slug: "booking-reservations",
    name: "Booking & Reservation Systems",
    tagline: "Fill Every Table",
    category: "Restaurant Technology",
    icon: "📅",
    metaDescription: "Online booking and reservation systems for restaurants. Automated confirmations, SMS reminders, waitlist management.",
    heroBody: "Let guests book tables online 24/7. Automated confirmations and reminders reduce no-shows and keep your dining room full.",
    features: [
      { icon: "🌐", title: "24/7 Online Booking", body: "Guests book directly from your website, Google, or Facebook at any hour." },
      { icon: "📱", title: "SMS & Email Confirmations", body: "Automatic booking confirmations and reminder texts sent to every guest." },
      { icon: "⏱️", title: "Waitlist Management", body: "Digital waitlist with text alerts when the table is ready — no paper needed." },
      { icon: "📊", title: "Reservation Analytics", body: "Track covers, peak times, no-show rates, and revenue per cover over time." },
      { icon: "🔗", title: "Google Reserve Integration", body: "Take reservations directly from your Google Business Profile listing." },
      { icon: "🔄", title: "Two-Way Sync", body: "Integrates with your existing POS and calendar so nothing gets double-booked." },
    ],
    benefits: ["Reduce no-shows by up to 40% with automated reminders", "Fill more seats with 24/7 online availability", "Eliminate phone tag with guests", "Build your customer database automatically"],
  },
  {
    slug: "menu-syncing",
    name: "Menu Syncing",
    tagline: "One Menu. Every Platform.",
    category: "Restaurant Technology",
    icon: "🔄",
    metaDescription: "Restaurant menu syncing across DoorDash, UberEats, Grubhub, and your website. Update once, sync everywhere.",
    heroBody: "Update your menu in one place and sync it instantly across your website, delivery apps, and ordering platforms.",
    features: [
      { icon: "🚀", title: "Update Once, Sync Everywhere", body: "Change a price or 86 an item and it updates on every platform within minutes." },
      { icon: "🛒", title: "Delivery App Integration", body: "Syncs with DoorDash, UberEats, Grubhub, and your commission-free ordering widget." },
      { icon: "📸", title: "Photo Management", body: "Upload item photos once and they appear consistently across all platforms." },
      { icon: "⚡", title: "Real-Time Availability", body: "Mark items as sold out in real-time so customers never order something you can't make." },
      { icon: "📋", title: "Category Organization", body: "Maintain organized categories, modifiers, and combos across all your channels." },
      { icon: "📊", title: "Performance Insights", body: "See which items sell best on which platform and optimize your menu accordingly." },
    ],
    benefits: ["Eliminate manual updates across multiple platforms", "Reduce order errors from outdated menus", "Save hours of management time weekly", "Keep branding consistent everywhere customers order"],
  },
  {
    slug: "menu-printing",
    name: "Menu Printing",
    tagline: "Design & Print",
    category: "Restaurant Technology",
    icon: "🖨️",
    metaDescription: "Professional restaurant menu design and printing. Print-ready menus, QR menus, and seasonal updates.",
    heroBody: "Professional menu design and print-ready files that match your brand. From dine-in menus to QR codes to seasonal inserts.",
    features: [
      { icon: "🎨", title: "Professional Menu Design", body: "Our designers create beautiful menus that match your restaurant's brand and atmosphere." },
      { icon: "📱", title: "QR Code Menus", body: "Digital QR menus that guests scan with their phone — no printing cost for updates." },
      { icon: "🖨️", title: "Print-Ready Files", body: "High-resolution print files formatted for any printer or commercial print shop." },
      { icon: "📅", title: "Seasonal Menu Updates", body: "Quarterly or seasonal menu redesigns to keep your offerings fresh and relevant." },
      { icon: "🔖", title: "Table Tents & Inserts", body: "Daily specials, happy hour promos, and dessert menus designed to upsell." },
      { icon: "✏️", title: "Unlimited Revisions", body: "We revise until you're happy. Your menu should be perfect before it hits the tables." },
    ],
    benefits: ["Menus that reflect your brand and drive higher check averages", "QR menus eliminate reprinting costs", "Professional photography integration available", "Fast turnaround — most menus delivered in 5–7 business days"],
  },
  // ── Web Services ──────────────────────────────────────────────
  {
    slug: "website-design",
    name: "Website Design",
    tagline: "Pre-Built & Custom",
    category: "Web Services",
    icon: "💻",
    metaDescription: "Restaurant and small business website design. Pre-built templates from $75/mo or fully custom builds.",
    heroBody: "Professional websites for restaurants and service businesses — mobile-first, SEO-ready, and delivered fast.",
    features: [],
    benefits: [],
    existingPage: "/websites",
  },
  {
    slug: "web-hosting",
    name: "Web Hosting",
    tagline: "Fast. Secure. Reliable.",
    category: "Web Services",
    icon: "☁️",
    metaDescription: "Managed web hosting for small businesses starting at $8/mo. WAF security, CDN, backups, 99.9% uptime.",
    heroBody: "Fast, secure hosting with backups, WAF security, CDN, and 99.9% uptime — starting at just $8/month.",
    features: [],
    benefits: [],
    existingPage: "/hosting",
  },
  {
    slug: "web-maintenance",
    name: "Web Maintenance",
    tagline: "Always Up to Date",
    category: "Web Services",
    icon: "🔧",
    metaDescription: "Website maintenance plans for restaurants and small businesses. Security updates, backups, edits, and support.",
    heroBody: "We keep your website secure, updated, and running perfectly so you can focus on your business.",
    features: [],
    benefits: [],
    existingPage: "/maintenance",
  },
  {
    slug: "ada-compliance",
    name: "ADA Compliance",
    tagline: "Protect Your Business",
    category: "Web Services",
    icon: "♿",
    metaDescription: "Website ADA compliance and WCAG 2.1 accessibility for restaurants and small businesses. Avoid lawsuits.",
    heroBody: "Make your website accessible to everyone and protect your business from ADA lawsuits with WCAG 2.1 compliance.",
    features: [
      { icon: "🔍", title: "Full Accessibility Audit", body: "We scan every page for WCAG 2.1 AA violations and document every issue found." },
      { icon: "♿", title: "Screen Reader Optimization", body: "Proper ARIA labels, semantic HTML, and keyboard navigation for assistive technology." },
      { icon: "🎨", title: "Color Contrast Fixes", body: "All text and UI elements meet minimum contrast ratios for visually impaired users." },
      { icon: "📸", title: "Alt Text Management", body: "Every image gets a descriptive alt tag so screen readers can describe your content." },
      { icon: "📋", title: "Compliance Certificate", body: "Receive a compliance report documenting your website's accessibility status." },
      { icon: "🔄", title: "Ongoing Monitoring", body: "Monthly scans to catch new violations as your content and site evolve." },
    ],
    benefits: ["Avoid costly ADA lawsuits that target restaurant websites", "Reach the 26% of adults with a disability", "Improve SEO — accessibility and search rankings are linked", "Show your community you welcome everyone"],
  },
  // ── Marketing ─────────────────────────────────────────────────
  {
    slug: "local-seo",
    name: "Local SEO & Citations",
    tagline: "Rank #1 in Your Area",
    category: "Marketing",
    icon: "📍",
    metaDescription: "Local SEO and citation building for restaurants. Rank higher on Google Maps and local search results.",
    heroBody: "Get found at the top of Google Maps and local search when hungry customers search for what you serve.",
    features: [],
    benefits: [],
    existingPage: "/restaurants/seo",
  },
  {
    slug: "google-ads",
    name: "Google Ads",
    tagline: "Pay-Per-Click Management",
    category: "Marketing",
    icon: "🔍",
    metaDescription: "Google Ads management for restaurants and small businesses. Search, display, and Performance Max campaigns.",
    heroBody: "Get to the top of Google search results instantly with expertly managed Google Ads campaigns that drive real customers.",
    features: [
      { icon: "🎯", title: "Search Campaigns", body: "Show up when customers search for 'restaurant near me' or your specific cuisine type." },
      { icon: "📍", title: "Local Campaigns", body: "Drive foot traffic with ads that target people within miles of your location." },
      { icon: "📊", title: "Performance Max", body: "AI-powered campaigns that serve ads across Search, YouTube, Maps, and Display automatically." },
      { icon: "🔄", title: "Remarketing", body: "Re-engage visitors who browsed your site or menu but didn't place an order." },
      { icon: "💰", title: "Budget Optimization", body: "We maximize every dollar with smart bidding strategies and negative keyword management." },
      { icon: "📈", title: "Monthly Reporting", body: "Clear reports on clicks, calls, orders, and cost per acquisition with zero jargon." },
    ],
    benefits: ["Appear above organic results immediately", "Only pay when someone clicks", "Target by location, time of day, and device", "Track phone calls and online orders as conversions"],
  },
  {
    slug: "social-media-ads",
    name: "Social Media Ads",
    tagline: "Facebook & Instagram",
    category: "Marketing",
    icon: "📱",
    metaDescription: "Facebook and Instagram ad management for restaurants. Targeted campaigns that drive online orders and foot traffic.",
    heroBody: "Reach your ideal customers on Facebook and Instagram with compelling ad campaigns that drive orders and reservations.",
    features: [
      { icon: "🎯", title: "Precise Audience Targeting", body: "Target by age, location, interests, dining habits, and lookalike audiences." },
      { icon: "🔄", title: "Retargeting Campaigns", body: "Reach people who visited your site, engaged with your page, or watched your videos." },
      { icon: "🎨", title: "Creative Design", body: "We design scroll-stopping graphics and video content that reflects your brand." },
      { icon: "🛒", title: "Conversion Campaigns", body: "Drive direct online orders with campaigns linked to your ordering system." },
      { icon: "📊", title: "A/B Testing", body: "We test multiple ad variations to find what resonates best with your audience." },
      { icon: "📈", title: "ROAS Tracking", body: "Track return on ad spend so you always know exactly what your campaigns are earning." },
    ],
    benefits: ["Reach customers where they spend the most time", "Highly visual platform perfect for food photography", "Build a local following and community", "Retarget warm audiences at a fraction of the cost"],
  },
  {
    slug: "ctv-ads",
    name: "CTV Cloud Ads",
    tagline: "Connected TV Advertising",
    category: "Marketing",
    icon: "📡",
    metaDescription: "CTV and Connected TV advertising for restaurants. Reach local streaming audiences on Hulu, Roku, and more.",
    heroBody: "Advertise on streaming platforms like Hulu, Roku, and Peacock — reaching local audiences who've cut the cord.",
    features: [
      { icon: "📺", title: "Premium Streaming Inventory", body: "Ads on Hulu, Roku, Peacock, Amazon Fire TV, and hundreds of streaming apps." },
      { icon: "📍", title: "Hyper-Local Targeting", body: "Target viewers within a specific radius of your restaurant, even down to zip code." },
      { icon: "🎬", title: "Video Creative Production", body: "We produce professional 15–30 second TV-quality ads for your restaurant." },
      { icon: "📊", title: "Cross-Device Attribution", body: "See when someone watches your CTV ad and then visits your website or orders online." },
      { icon: "🔄", title: "Sequential Storytelling", body: "Show a series of ads to build awareness, then drive action with a strong offer." },
      { icon: "💰", title: "Budget-Friendly Entry", body: "CTV is now accessible to local restaurants — no massive TV ad budget required." },
    ],
    benefits: ["Reach cord-cutters who no longer see traditional TV ads", "Premium, unskippable ad placement", "100% viewability — viewers can't scroll past", "More affordable than traditional broadcast TV"],
  },
  {
    slug: "photography",
    name: "Photography Services",
    tagline: "Food & Restaurant Photography",
    category: "Marketing",
    icon: "📸",
    metaDescription: "Professional food and restaurant photography in South Florida. Menu photos, interior shots, and social media content.",
    heroBody: "Professional food photography and restaurant imagery that makes customers hungry before they even walk in the door.",
    features: [
      { icon: "🍽️", title: "Food Photography", body: "Studio-quality food shots that make every dish look irresistible on menus and social media." },
      { icon: "🏠", title: "Interior & Atmosphere", body: "Capture the ambiance of your dining room, bar, and kitchen to attract the right guests." },
      { icon: "👨‍🍳", title: "Chef & Staff Portraits", body: "Professional headshots and candid team photos that humanize your brand." },
      { icon: "📱", title: "Social Media Content", body: "Vertical and square crops, Reels-ready clips, and Story formats included." },
      { icon: "🎬", title: "Video Walk-Throughs", body: "Short cinematic video tours of your restaurant for Google Business and social." },
      { icon: "📦", title: "Full Usage Rights", body: "All photos are yours — use on website, menu, social, ads, and Google anywhere." },
    ],
    benefits: ["Menus with photos see 30% higher order values", "Stand out on Google with professional imagery", "Consistent visual brand across all platforms", "Content library for months of social posts"],
  },
  // ── AI & Automation ───────────────────────────────────────────
  {
    slug: "ai-workflows",
    name: "AI Workflows & Automation",
    tagline: "Put Business on Autopilot",
    category: "AI & Automation",
    icon: "🤖",
    metaDescription: "AI workflow automation for restaurants and small businesses. Chatbots, voice agents, and automated follow-ups.",
    heroBody: "AI-powered workflows that automate repetitive tasks — from answering customer questions to sending review requests.",
    features: [],
    benefits: [],
    existingPage: "/ai-automation",
  },
  {
    slug: "ai-chatbots",
    name: "AI Chat Bots",
    tagline: "24/7 Customer Service",
    category: "AI & Automation",
    icon: "💬",
    metaDescription: "AI chatbots for restaurants — answer questions, take reservations, and handle orders 24/7 automatically.",
    heroBody: "An AI chatbot trained on your restaurant's menu, hours, and FAQs — answering customer questions around the clock.",
    features: [
      { icon: "🧠", title: "Trained on Your Data", body: "The chatbot knows your menu, hours, location, parking, policies, and FAQs inside out." },
      { icon: "💬", title: "Website & Facebook", body: "Deploy on your website chat widget, Facebook Messenger, and Instagram DMs." },
      { icon: "🛒", title: "Order Initiation", body: "The bot can walk customers through your menu and direct them to your ordering link." },
      { icon: "📅", title: "Reservation Booking", body: "Collect reservation details and add them directly to your booking system." },
      { icon: "🔄", title: "Escalation to Human", body: "When the bot can't help, it seamlessly hands off to your staff with full context." },
      { icon: "📊", title: "Conversation Analytics", body: "See what customers ask most often to improve your menu and FAQ content." },
    ],
    benefits: ["Handle 80% of common questions without staff involvement", "Never miss an inquiry at 2am", "Capture leads from every chat conversation", "Reduce phone calls so staff focuses on in-person guests"],
  },
  {
    slug: "ai-surveillance",
    name: "AI Surveillance",
    tagline: "Smart Security",
    category: "AI & Automation",
    icon: "📷",
    metaDescription: "AI-powered surveillance and security cameras for restaurants. Smart alerts, remote monitoring, cloud storage.",
    heroBody: "Smart security cameras with AI that recognizes motion, unusual activity, and sends instant alerts to your phone.",
    features: [
      { icon: "🧠", title: "AI Motion Detection", body: "Distinguish between people, vehicles, and animals — only alert on what matters." },
      { icon: "☁️", title: "Cloud Storage", body: "Footage stored securely in the cloud — accessible from anywhere, no DVR required." },
      { icon: "📱", title: "Remote Monitoring", body: "Watch your restaurant live from your phone, tablet, or computer anywhere in the world." },
      { icon: "⚡", title: "Instant Alerts", body: "Get push notifications the moment suspicious activity is detected after hours." },
      { icon: "🔗", title: "Multi-Location Support", body: "Monitor all your locations from a single app dashboard." },
      { icon: "📊", title: "Customer Analytics", body: "AI counts foot traffic, peak hours, and queue length to optimize staffing." },
    ],
    benefits: ["Deter theft and vandalism with visible smart cameras", "Resolve disputes with HD video evidence", "Monitor staff and operations remotely", "Reduce insurance premiums with documented security"],
  },
  // ── Operations ────────────────────────────────────────────────
  {
    slug: "payment-portals",
    name: "Payment Portals",
    tagline: "Get Paid Faster",
    category: "Operations",
    icon: "💳",
    metaDescription: "Online payment portals for restaurants and service businesses. Invoicing, payment links, and recurring billing.",
    heroBody: "Professional online payment portals — send invoices, collect deposits, and accept payments from anywhere.",
    features: [
      { icon: "🔗", title: "Payment Links", body: "Send a simple link via text or email that customers click to pay instantly." },
      { icon: "📋", title: "Professional Invoicing", body: "Branded invoices with your logo, itemized charges, and automatic payment reminders." },
      { icon: "🔄", title: "Recurring Billing", body: "Set up automatic monthly or weekly billing for catering clients and maintenance contracts." },
      { icon: "💳", title: "All Payment Methods", body: "Accept credit cards, debit, ACH bank transfer, Apple Pay, and Google Pay." },
      { icon: "📊", title: "Payment Dashboard", body: "Track outstanding invoices, payment history, and cash flow in one dashboard." },
      { icon: "🔒", title: "PCI Compliant", body: "Bank-level security with PCI DSS compliance — your customers' data is always safe." },
    ],
    benefits: ["Get paid 3x faster with digital invoices vs. paper", "Reduce awkward payment conversations", "Accept deposits to secure catering and private events", "Automatic late payment reminders"],
  },
  {
    slug: "qr-codes",
    name: "QR Code Management",
    tagline: "Smart QR Codes",
    category: "Operations",
    icon: "⬛",
    metaDescription: "Dynamic QR code management for restaurants. Menu QR codes, WiFi codes, ordering links, and analytics.",
    heroBody: "Create, manage, and track QR codes for your menu, WiFi, ordering, and promotions — all from one dashboard.",
    features: [
      { icon: "🔄", title: "Dynamic QR Codes", body: "Change where a QR code points without reprinting — update your menu link instantly." },
      { icon: "🍽️", title: "Menu QR Codes", body: "Table QR codes that open your digital menu — no app required for guests." },
      { icon: "📶", title: "WiFi QR Codes", body: "One scan to connect guests to your WiFi — no password typing needed." },
      { icon: "🛒", title: "Ordering QR Codes", body: "Direct guests from table to your online ordering system with one scan." },
      { icon: "📊", title: "Scan Analytics", body: "See how many times each QR code was scanned, when, and from which location." },
      { icon: "🎨", title: "Branded Designs", body: "Custom QR code designs with your logo and brand colors — not boring black squares." },
    ],
    benefits: ["Eliminate menu printing costs with QR menus", "Track engagement with every printed marketing piece", "Update destinations without reprinting materials", "Capture WiFi users for email marketing"],
  },
  {
    slug: "managed-wifi",
    name: "Managed WiFi Networks",
    tagline: "Smart Guest WiFi",
    category: "Operations",
    icon: "📶",
    metaDescription: "Managed WiFi networks for restaurants. Guest WiFi with email capture, marketing integration, and network management.",
    heroBody: "Enterprise-grade WiFi for your restaurant with guest marketing capture, network management, and multi-location support.",
    features: [
      { icon: "📧", title: "Guest Email Capture", body: "Every guest who connects to your WiFi optionally provides their email for your list." },
      { icon: "🔒", title: "Network Segmentation", body: "Separate guest and staff networks so your POS and business data stay secure." },
      { icon: "⚡", title: "High-Performance Hardware", body: "Commercial-grade access points installed and configured for your floor plan." },
      { icon: "📊", title: "Usage Analytics", body: "See peak usage times, connected device counts, and bandwidth consumption." },
      { icon: "🌐", title: "Multi-Location Management", body: "Manage all your locations' WiFi networks from a single cloud dashboard." },
      { icon: "🛠️", title: "Remote Support", body: "We monitor and troubleshoot your network remotely — most issues resolved without a visit." },
    ],
    benefits: ["Build your email list with every WiFi login", "Protect your POS system from guest network access", "Eliminate WiFi dead zones with proper coverage planning", "Offer premium guest experience"],
  },
  {
    slug: "pop-displays",
    name: "POP Displays",
    tagline: "Point of Purchase",
    category: "Operations",
    icon: "🎯",
    metaDescription: "Point of purchase displays for restaurants. Counter displays, window graphics, table tents, and custom print design.",
    heroBody: "Eye-catching point-of-purchase displays that drive impulse decisions — at the counter, at the table, and in your window.",
    features: [
      { icon: "🎨", title: "Custom Design", body: "Professional graphic design for all your POP display needs, matching your brand." },
      { icon: "🏪", title: "Counter Displays", body: "Upsell desserts, drinks, and add-ons with strategically placed counter displays." },
      { icon: "🪟", title: "Window Graphics", body: "Eye-catching window clings and decals that stop foot traffic and communicate your offers." },
      { icon: "📋", title: "Table Tents", body: "Promote specials, events, online ordering, and loyalty programs at every table." },
      { icon: "🛒", title: "Promo Signage", body: "Happy hour boards, daily special signs, and seasonal promotion displays." },
      { icon: "🔄", title: "Seasonal Updates", body: "Refresh your displays seasonally or for special events and holidays." },
    ],
    benefits: ["Increase average check with strategic upsell placement", "Drive awareness of online ordering and loyalty programs", "Reinforce your brand throughout the customer journey", "Cost-effective marketing that works while you sleep"],
  },
];

export const categories = ["All", "Restaurant Technology", "Web Services", "Marketing", "AI & Automation", "Operations"];

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find((s) => s.slug === slug);
}

export function getServicesByCategory(category: string): ServiceData[] {
  if (category === "All") return servicesData;
  return servicesData.filter((s) => s.category === category);
}

export const serviceSlugMap: Record<string, string> = {
  "AI Workflows & Automation": "/services/ai-workflows",
  "Online Ordering": "/services/online-ordering",
  "POS Systems": "/services/pos-systems",
  "Website Design": "/services/website-design",
  "Web Hosting": "/services/web-hosting",
  "Booking & Reservation Systems": "/services/booking-reservations",
  "Payment Portals": "/services/payment-portals",
  "Menu Syncing": "/services/menu-syncing",
  "Menu Printing": "/services/menu-printing",
  "Digital Signage": "/services/digital-signage",
  "AI Chat Bots": "/services/ai-chatbots",
  "Local SEO & Citations": "/services/local-seo",
  "Photography Services": "/services/photography",
  "QR Code Management": "/services/qr-codes",
  "Google Ads": "/services/google-ads",
  "Social Media Ads": "/services/social-media-ads",
  "CTV Cloud Ads": "/services/ctv-ads",
  "AI Surveillance": "/services/ai-surveillance",
  "Managed WiFi Networks": "/services/managed-wifi",
  "ADA Compliance": "/services/ada-compliance",
  "POP Displays": "/services/pop-displays",
  "Web Maintenance": "/services/web-maintenance",
};
